### ISSUE TITLE
Implement DID Document Structure and update storage

### ISSUE THREAD

**Issue by juanmagiraldor** [kommitters/soroban-did-contract#20]
## Objective

Implement DID Document struct and update storage.

## Checklist
1. **Implement DID Document Struct:**
    - Create a robust **`DIDDocument`** struct to comprehensively represent Decentralized Identifiers (DIDs) along with their associated information.
2. **Revise Storage to Save Only a DID Document:**
    - Modify the storage mechanism to exclusively store a single **`DIDDocument`** for each Decentralized Identifier.
    - Ensure that the storage design aligns with the updated **`DIDDocument`** structure.
3. **Reflect All Changes in the DID Document:**
    - Ensure that any modifications or updates in the contract, particularly related to DIDs, are accurately and consistently reflected in the associated **`DIDDocument`**.
4. **Return DID Document in All Functions:**
    - Modify existing functions to return the updated **`DIDDocument`** after any operations.
    - This ensures a cohesive and straightforward approach, providing a complete snapshot of the DID Document post-function execution.

**Comment by miguelnietoa** [comment]
Implemented and available at [`v0.2.0`](https://github.com/kommitters/soroban-did-contract/releases/tag/v0.2.0)
